# Generated by Django 4.1.6 on 2023-03-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('riverid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_of_river', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('collector', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('altitude', models.IntegerField()),
            ],
        ),
    ]
