# Generated by Django 4.1.6 on 2023-03-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='habitatparameter',
            fields=[
                ('siteid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_of_river', models.CharField(max_length=200)),
                ('name_of_the_site', models.CharField(max_length=200)),
                ('altitude_MSL', models.IntegerField()),
                ('habitattype', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('Substratepercent', models.IntegerField()),
                ('boulders', models.CharField(max_length=200)),
                ('Cobbles', models.CharField(max_length=200)),
                ('Pebbles', models.CharField(max_length=200)),
                ('Gravels', models.CharField(max_length=200)),
                ('Sand', models.CharField(max_length=200)),
                ('SiltandClay', models.CharField(max_length=200)),
                ('Aquaticpercent', models.IntegerField()),
                ('Floating', models.CharField(max_length=200)),
                ('Submerged', models.CharField(max_length=200)),
                ('Emerged', models.CharField(max_length=200)),
                ('Other', models.CharField(max_length=200)),
                ('water_color', models.CharField(max_length=200)),
                ('riparian_vegetation', models.IntegerField()),
                ('water_velocity', models.IntegerField()),
                ('temp_Air', models.IntegerField()),
                ('temp_Water', models.IntegerField()),
                ('pH', models.IntegerField()),
                ('turbidity', models.IntegerField()),
                ('riverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.form')),
            ],
        ),
    ]
