# Generated by Django 4.1.6 on 2023-04-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_fishbiodiversity_primary_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fishbiodiversity_primary',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fishbiodiversitysec',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fishbioforexoticfish',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fishtable',
            table=None,
        ),
        migrations.AlterModelTable(
            name='form',
            table=None,
        ),
        migrations.AlterModelTable(
            name='habitatparameter',
            table=None,
        ),
    ]
